### ISSUE TITLE
GridSearch::CheckConstraints use grid_xy to do collision check with cartisian  line_segment obstacle

### ISSUE THREAD

**Issue by hoppss** [LLLLLyra/hybrid_a_star_g2#1]
bool GridSearch::CheckConstraints

do collision check use gridindex in node2d and line segment obstacle in cartesian.

**Comment by LLLLLyra** [comment]
> bool GridSearch::CheckConstraints
> 
> 
> 
> do collision check use gridindex in node2d and line segment obstacle in cartesian.

Hi Hoppss,

Thanks for your comment.

GridSearch just conducts standard A* search to get cost of each Node2d. I couldn't tell any unreasonable reasons to check collision in Cartesian.

**Comment by hoppss** [comment]
> > bool GridSearch::CheckConstraints
> > do collision check use gridindex in node2d and line segment obstacle in cartesian.
> 
> Hi Hoppss,
> 
> Thanks for your comment.
> 
> GridSearch just conducts standard A* search to get cost of each Node2d. I couldn't tell any unreasonable reasons to check collision in Cartesian.

**Comment by hoppss** [comment]
Hi,
Thanks for your response.
Node2d xy is grid index, but it is used to do collision check obstacle linesegment while obstacle is at cartisian coordinate ?

**Comment by LLLLLyra** [comment]
> Hi,
> 
> Thanks for your response.
> 
> Node2d xy is grid index, but it is used to do collision check obstacle linesegment while obstacle is at cartisian coordinate ?

Hi,

Sorry for the overdue response. 

Yes, you could check collision in Cartesian Coordinate.
